  <?php
  use FileCMS\Common\Generic\Messages;
  $message = Messages::getInstance();
  $msg = $message->getMessages() ?? 'Unknown Error';
  ?>
  <!-- Header -->
  <header class="bg-primary py-5 mb-5">
    <div class="container h-100">
      <div class="row h-100 align-items-center">
        <div class="col-lg-12">
          <h1 class="display-4 text-white mt-5 mb-2">Sorry!</h1>
          <p class="lead mb-5 text-white-50">Looks like we ran into a problem on our end.
          Please contact the site administrator.</p>
        </div>
      </div>
    </div>
  </header>

  <!-- Page Content -->
  <div class="container">

    <div class="row">
      <div class="col-md-8 mb-5">
        <h2>Sorry!</h2>
        <hr>
        <p>Looks like we ran into a problem.  This is the message received just now: </p>
        <pre><?= $msg ?></pre>
        <a class="btn btn-primary btn-lg" href="/contact">Contact &raquo;</a>
      </div>
      <div class="col-md-4 mb-5">
        <h2>Contact Us</h2>
        <hr>
        Click on the button to the left
      </div>
    </div>
    <!-- /.row -->

  </div>
  <!-- /.container -->
