<?php
use FileCMS\Common\Generic\Messages;
$message = Messages::getInstance();
$msg = $message->getMessages();
?>

  <!-- Header -->
  <header class="bg-primary py-5 mb-5">
    <div class="container h-100">
      <div class="row h-100 align-items-center">
        <div class="col-lg-12">
          <h1 class="display-4 text-white mt-5 mb-2">PHP Training</h1>
          <p class="lead mb-5 text-white-50">K through 12 education often misses the boat when it comes to teaching basic programming concepts.
          On this website we offer K - 12 training on computer basics using the gaming model.</p>
        </div>
      </div>
    </div>
  </header>

  <!-- Page Content -->
  <div class="container">

    <div class="row">
    %%TRAINING%%
    </div>
    <div class="row">
    %%ARTICLES=3%%
    </div>
    <!-- /.row -->

    <?php if (!empty($msg)) : ?>
    <div class="row">
        <div class="col-md-12">
            <div class="alert alert-success contact__msg">
                <?= $msg ?>
            </div>
        </div>
    </div>
    <?php endif; ?>

  </div>
  <!-- /.container -->
